controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    use_sim_time: true
    hunter_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true
    hunter_ackermann_drive_controller:
      type: ackermann_steering_controller/AckermannSteeringController

hunter_effort_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint
      - front_left_steering_joint
      - front_right_steering_joint
      - steering_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity

hunter_ackermann_drive_controller:
  ros__parameters:
    front_left_wheel_joint: front_left_wheel_joint
    front_right_wheel_joint: front_right_wheel_joint
    rear_left_wheel_joint: rear_left_wheel_joint
    rear_right_wheel_joint: rear_right_wheel_joint
    front_left_steering_joint: front_left_steering_joint
    front_right_steering_joint: front_right_steering_joint
    steering_wheel_joint: steering_joint

    max_steer: 0.6458
    max_steering_angle: 7.85
    max_speed: 20

    left_steering_pid_gain: [1000, 10, 1]
    left_steering_i_range: [0, 0]
    right_steering_pid_gain: [1000, 10, 1]
    right_steering_i_range: [0, 0]
    linear_velocity_pid_gain: [1000, 10, 1]
    linear_velocity_i_range: [0, 0]

    publish_odom: true
    publish_odom_tf: true
    publish_wheel_tf: false
    publish_distance: true

    odometry_frame: odom
    robot_base_frame: base_link